export enum RoleEnum {
  SYSTEMADMIN = 'SYSTEMADMIN', // SYSTEM...
  SUPERADMIN = 'SUPERADMIN', // GET ALL DATA
  ADMIN = 'ADMIN', // JUST GET THEIR REGION
  LEADER = 'LEADER', // JUST GET THEIR REGION
  PEMIMPIN_PERSEKUTUAN = 'PEMIMPIN_PERSEKUTUAN', // JUST GET THEIR GROUP
  PEMBIMBING = 'PEMBIMBING', // JUST GET THEIR CHILD
}
