export enum RoleEnum {
  ROLE_SYSTEMADMIN = 'SYSTEMADMIN', // SYSTEM...
  ROLE_SUPERADMIN = 'SUPERADMIN', // GET ALL DATA
  LEADER = 'LEADER', // JUST GET THEIR COMMUNITY
  PARENT = 'PARENT', // JUST GET THEIR DISCIPLES_CHILD
}
